In [3]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\rajni\AppData\Roaming\Python\Python314\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\rajni\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\rajni\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\rajni\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\rajni\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd

In [5]:
df1 = pd.read_csv(r"C:\Users\rajni\OneDrive\Desktop\python\data cleaning\churn_data.csv")

In [6]:
df2 = pd.read_csv(r"C:\Users\rajni\OneDrive\Desktop\python\data cleaning\customer_data.csv")

In [7]:
df3 = pd.read_csv(r"C:\Users\rajni\OneDrive\Desktop\python\data cleaning\internet_data.csv")

In [8]:
df1.head()

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,34,Yes,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,2,Yes,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,45,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [9]:
df2.head()

   customerID  gender  SeniorCitizen Partner Dependents
0  7590-VHVEG  Female              0     Yes         No
1  5575-GNVDE    Male              0      No         No
2  3668-QPYBK    Male              0      No         No
3  7795-CFOCW    Male              0      No         No
4  9237-HQITU  Female              0      No         No

In [10]:
df3.head()

,customerID,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,No phone service,DSL,No,Yes,No,No,No,No
1,5575-GNVDE,No,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,No,DSL,Yes,Yes,No,No,No,No
3,7795-CFOCW,No phone service,DSL,Yes,No,Yes,Yes,No,No
4,9237-HQITU,No,Fiber optic,No,No,No,No,No,No

In [11]:
print('shape of df1:',df1.shape)
print('shape of df2:',df2.shape)
print('shape of df3:',df3.shape)

shape of df1: (7043, 9)
shape of df2: (7043, 5)
shape of df3: (7043, 9)

In [12]:
print(df1.info())

print("----------------------------------------------")
print(df2.info())
print("----------------------------------------------")
print(df3.info())

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   tenure            7043 non-null   int64
 2   PhoneService      7043 non-null   str
 3   Contract          7043 non-null   str
 4   PaperlessBilling  7043 non-null   str
 5   PaymentMethod     7043 non-null   str
 6   MonthlyCharges    7043 non-null   float64
 7   TotalCharges      7043 non-null   str
 8   Churn             7043 non-null   str
dtypes: float64(1), int64(1), str(7)
memory usage: 495.3 KB
None
----------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerID     7043 non-null   str
 1   gender         7043 non-null   str
 2   SeniorCitizen  7043 non-null   int64
 3   Partner        7043 non-null   str
 4   Dependents     7043 non-null   str
dtypes: int64(1), str(4)
memory usage: 275.2 KB
None
----------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   MultipleLines     7043 non-null   str
 2   InternetService   7043 non-null   str
 3   OnlineSecurity    7043 non-null   str
 4   OnlineBackup      7043 non-null   str
 5   DeviceProtection  7043 non-null   str
 6   TechSupport       7043 non-null   str
 7   StreamingTV       7043 non-null   str
 8   StreamingMovies   7043 non-null   str
dtypes: str(9)
memory usage: 495.3 KB
None

In [13]:
df1['TotalCharges']=pd.to_numeric(df1['TotalCharges'], errors='coerce')

In [14]:
print('duplicate values of df1', df1.duplicated().sum())
print('duplicate values of df2', df2.duplicated().sum())
print('duplicate values of df3', df3.duplicated().sum())

duplicate values of df1 0
duplicate values of df2 0
duplicate values of df3 0

In [15]:
df1.columns=df1.columns.str.lower().str.replace(" ","_")
df2.columns=df2.columns.str.lower().str.replace(" ","_")
df3.columns=df3.columns.str.lower().str.replace(" ","_")

In [16]:
new_df=pd.merge(df1,df2, on='customerid', how='inner')

df=pd.merge(new_df,df3,on='customerid', how='inner')

In [17]:
df.isnull().sum()

df.dropna(inplace=True)

df.isnull().sum()

customerid          0
tenure              0
phoneservice        0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
gender              0
seniorcitizen       0
partner             0
dependents          0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
dtype: int64

In [18]:
df['churn'].value_counts(normalize= True)*100

churn
No     73.421502
Yes    26.578498
Name: proportion, dtype: float64

In [ ]:
import matplotlib

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
df['churn'].value_counts(normalize= True).plot(kind='pie')

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

In [ ]:
df.groupby('internetservice')['monthlycharges'].agg([
    'mean', 'max', 'min'
])

                      mean     max    min
internetservice
DSL              58.088017   94.80  23.45
Fiber optic      91.500129  118.75  67.75
No               21.076283   26.90  18.25

In [ ]:
df.groupby('internetservice')['tenure'].mean()

internetservice
DSL            32.889487
Fiber optic    32.917959
No             30.667763
Name: tenure, dtype: float64

In [ ]:
df['paymentmethod'].value_counts().head()

paymentmethod
Electronic check             2365
Mailed check                 1604
Bank transfer (automatic)    1542
Credit card (automatic)      1521
Name: count, dtype: int64

In [ ]:
df.groupby('churn')['monthlycharges'].mean()

churn
No     61.307408
Yes    74.441332
Name: monthlycharges, dtype: float64

In [ ]:
df[(df['monthlycharges'] > 80) & (df['churn']=='Yes')]

,customerid,tenure,phoneservice,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn,gender,...,partner,dependents,multiplelines,internetservice,onlinesecurity,onlinebackup,deviceprotection,techsupport,streamingtv,streamingmovies
5,9305-CDSKC,8,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,Yes,Female,...,No,No,Yes,Fiber optic,No,No,Yes,No,Yes,Yes
8,7892-POOKP,28,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,Female,...,Yes,No,Yes,Fiber optic,No,No,Yes,Yes,Yes,Yes
13,0280-XJGEX,49,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,Yes,Male,...,No,No,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes
26,6467-CHFZW,47,Yes,Month-to-month,Yes,Electronic check,99.35,4749.15,Yes,Male,...,Yes,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,Yes
38,5380-WJKOV,34,Yes,Month-to-month,Yes,Electronic check,106.35,3549.25,Yes,Male,...,No,No,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6991,3585-ISXZP,8,Yes,Month-to-month,No,Bank transfer (automatic),95.65,778.10,Yes,Female,...,No,No,Yes,Fiber optic,No,No,No,No,Yes,Yes
6993,6583-QGCSI,50,Yes,Month-to-month,Yes,Electronic check,88.05,4367.35,Yes,Female,...,Yes,No,Yes,Fiber optic,No,Yes,No,No,Yes,No
7006,0093-XWZFY,40,Yes,Month-to-month,Yes,Credit card (automatic),104.50,4036.85,Yes,Male,...,No,No,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes
7009,7703-ZEKEF,23,Yes,Month-to-month,Yes,Electronic check,81.00,1917.10,Yes,Male,...,No,No,Yes,Fiber optic,No,No,Yes,No,No,No
7034,0639-TSIQW,67,Yes,Month-to-month,Yes,Credit card (automatic),102.95,6886.25,Yes,Female,...,No,No,Yes,Fiber optic,Yes,Yes,Yes,No,Yes,No

In [ ]:
(df['monthlycharges'] > 80) & (df['churn']=='Yes').sum()

0       False
1       False
2       False
3       False
4       False
        ...
7038     True
7039     True
7040    False
7041    False
7042     True
Name: monthlycharges, Length: 7032, dtype: bool

In [ ]:
df.loc[df['tenure']>24,['customerid', 'gender', 'monthlycharges','contract']]

      customerid  gender  monthlycharges        contract
1     5575-GNVDE    Male           56.95        One year
3     7795-CFOCW    Male           42.30        One year
8     7892-POOKP  Female          104.80  Month-to-month
9     6388-TABGU    Male           56.15        One year
12    8091-TTVAX    Male          100.35        One year
...          ...     ...             ...             ...
7033  9767-FFLEM    Male           69.50  Month-to-month
7034  0639-TSIQW  Female          102.95  Month-to-month
7037  2569-WGERO  Female           21.15        Two year
7039  2234-XADUH  Female          103.20        One year
7042  3186-AJIEK    Male          105.65        Two year

[3833 rows x 4 columns]

In [ ]:
df.iloc[50:61,2:8]

,phoneservice,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges
50,Yes,Month-to-month,Yes,Electronic check,90.25,3838.75
51,Yes,Month-to-month,Yes,Credit card (automatic),99.10,1426.40
52,Yes,Month-to-month,Yes,Credit card (automatic),69.50,1752.65
53,Yes,Month-to-month,Yes,Credit card (automatic),80.65,633.30
54,Yes,One year,Yes,Credit card (automatic),74.85,4456.35
55,Yes,Month-to-month,Yes,Electronic check,95.45,1752.55
56,Yes,One year,Yes,Credit card (automatic),99.65,6311.20
57,Yes,One year,Yes,Electronic check,108.45,7076.35
58,Yes,Two year,No,Credit card (automatic),24.95,894.30
59,Yes,Two year,Yes,Credit card (automatic),107.50,7853.70
60,Yes,Month-to-month,Yes,Electronic check,100.50,4707.10

In [ ]:
df[(df['internetservice']=='Fiber optic') & 
   (df['paymentmethod']=='Electronic check')]

,customerid,tenure,phoneservice,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn,gender,...,partner,dependents,multiplelines,internetservice,onlinesecurity,onlinebackup,deviceprotection,techsupport,streamingtv,streamingmovies
4,9237-HQITU,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,Female,...,No,No,No,Fiber optic,No,No,No,No,No,No
5,9305-CDSKC,8,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,Yes,Female,...,No,No,Yes,Fiber optic,No,No,Yes,No,Yes,Yes
8,7892-POOKP,28,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,Female,...,Yes,No,Yes,Fiber optic,No,No,Yes,Yes,Yes,Yes
14,5129-JLPIS,25,Yes,Month-to-month,Yes,Electronic check,105.50,2686.05,No,Male,...,No,No,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes
19,4183-MYFRB,21,Yes,Month-to-month,Yes,Electronic check,90.05,1862.90,No,Female,...,No,No,No,Fiber optic,No,Yes,Yes,No,No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7010,0723-DRCLG,1,Yes,Month-to-month,Yes,Electronic check,74.45,74.45,Yes,Female,...,Yes,No,Yes,Fiber optic,No,No,No,No,No,No
7014,9053-EJUNL,41,Yes,Month-to-month,Yes,Electronic check,89.20,3645.75,No,Male,...,No,No,Yes,Fiber optic,No,Yes,No,No,Yes,No
7022,7203-OYKCT,72,Yes,One year,Yes,Electronic check,104.95,7544.30,No,Male,...,No,No,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes
7023,1035-IPQPU,63,Yes,Month-to-month,Yes,Electronic check,103.50,6479.40,No,Female,...,Yes,No,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes
7032,6894-LFHLY,1,Yes,Month-to-month,Yes,Electronic check,75.75,75.75,Yes,Male,...,No,No,Yes,Fiber optic,No,No,No,No,No,No

In [ ]:
df.groupby('contract')[['monthlycharges', 'tenure']].agg(
    ['mean', 'min', 'max']
)

               monthlycharges                    tenure
                         mean    min     max       mean min max
contract
Month-to-month      66.398490  18.75  117.45  18.036645   1  72
One year            65.079416  18.25  118.60  42.073370   1  72
Two year            60.872374  18.40  118.75  57.071810   1  72

In [ ]:
df['annualcharges']=df['monthlycharges']*12
df['annualcharges']

0        358.2
1        683.4
2        646.2
3        507.6
4        848.4
         ...
7038    1017.6
7039    1238.4
7040     355.2
7041     892.8
7042    1267.8
Name: annualcharges, Length: 7032, dtype: float64

In [ ]:
def converter(x):
    if x<12:
        return 'new'
    elif 12<=x<=48:
        return 'regular'
    else:
        return 'loyal'




df['customertype']=df['tenure'].apply(converter)
df['customertype']

0           new
1       regular
2           new
3       regular
4           new
         ...
7038    regular
7039      loyal
7040        new
7041        new
7042      loyal
Name: customertype, Length: 7032, dtype: str

In [ ]:
df.sort_values(by='annualcharges', ascending = False)[['customerid', 'contract', 'monthlycharges', 'annualcharges', 'churn']].head(10)

      customerid        contract  monthlycharges  annualcharges churn
4586  7569-NMZYQ        Two year          118.75         1425.0    No
2115  8984-HPEMB        Two year          118.65         1423.8    No
4804  5734-EJKXG        One year          118.60         1423.2    No
3894  5989-AXPUC        Two year          118.60         1423.2    No
5127  8199-ZLLSA        One year          118.35         1420.2   Yes
6118  9924-JPRMC        Two year          118.20         1418.4    No
4610  2889-FPWRM        One year          117.80         1413.6   Yes
3205  3810-DVDQQ        Two year          117.60         1411.2    No
6768  9739-JLPQJ        Two year          117.50         1410.0    No
4875  2302-ANTDP  Month-to-month          117.45         1409.4   Yes